# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list. 



Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [31]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_core', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_ex

In [33]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
arr = [0] * 10
np_array = np.array(arr)

print(np_array)

[0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)

In [37]:
print("Memory:",np_array.nbytes)

### alternative
print("Memory:",np_array.size * (np_array[0].nbytes))

Memory: 40
Memory: 40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [221]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [3]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [23]:
### Using arange function 
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [39]:
reverse_arr = arr[::-1]
print(reverse_arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [29]:
arr_3_3 = 

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [46]:
arr_3by3 = np.arange(0,9).reshape(3,3)
print(arr_3by3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [80]:
identity_3_3 = np.eye(3,3)
print(identity_3_3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [64]:
random_values_matrix = np.random.rand(3,3,3)

print(random_values_matrix)

[[[0.57902148 0.91337927 0.32228348]
  [0.81233526 0.99617849 0.68112654]
  [0.73628873 0.72412367 0.67177623]]

 [[0.99558139 0.74092598 0.01457798]
  [0.10728593 0.70360559 0.73435555]
  [0.9823521  0.44430548 0.769517  ]]

 [[0.59796984 0.27860354 0.46785745]
  [0.04041739 0.03821366 0.9459953 ]
  [0.78713759 0.75638442 0.83774423]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [98]:
arr = np.random.rand(10,10)
max_val = np.max(arr.reshape(-1))
min_val = np.min(arr.reshape(-1))
print(max_val)
print(min_val)

0.9964028511860966
0.011004542760197245


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [100]:
arr = np.random.rand(30)
avg = np.mean(arr)
print("Average value:",avg)

Average value: 0.4854462586922433


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [126]:
row = 10
col = 10

arr = np.ones((row,col))
arr[1:row - 1,1:col - 1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [146]:
arr = np.ones((row,col))
padded_arr = np.zeros((row + 2,col + 2))

padded_arr[1 : -1,1 : - 1] = arr

print(padded_arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [170]:
print("0 * np.nan:",0 * np.nan)
print("np.nan == np.nan : ",np.nan == np.nan)
print("np.inf > np.nan : ",np.inf > np.nan)
print("np.nan - np.nan:",np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

0 * np.nan: nan
np.nan == np.nan :  False
np.inf > np.nan :  False
np.nan - np.nan: nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [219]:
matrix = np.zeros((5, 5), dtype=int)
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [211]:
chess_board = np.zeros((8,8),dtype=int)
chess_board[1::2,::2] = 1
chess_board[::2,1::2] = 1
print(chess_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [217]:
index = np.unravel_index(99, (6,7,8))
print(index)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [205]:
pattern1 = np.tile([1,0],4)
pattern2 = np.tile([0,1],4)

chess_board = np.zeros((8,8))
chess_board[::2] = pattern1
chess_board[1::2] = pattern2

print(chess_board)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [213]:
matrix = np.random.rand(5, 5)

normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))

print("\nNormalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[0.97266534 0.87525412 0.97701218 0.27554794 0.94085896]
 [0.69465902 0.48352144 0.12083052 0.42105924 0.75110686]
 [0.32503034 0.23894337 0.03548767 0.49023768 0.46605852]
 [0.95108523 0.4603851  0.26847989 0.92719373 0.29405124]
 [0.94573573 0.92250613 0.16267048 0.02301433 0.1778514 ]]

Normalized Matrix:
 [[0.99544356 0.89333513 1.         0.26471088 0.96210346]
 [0.70403166 0.48271295 0.10253292 0.4172388  0.76320144]
 [0.31657934 0.22634123 0.01307481 0.48975304 0.46440796]
 [0.97282284 0.45846096 0.25730201 0.94777929 0.28410641]
 [0.96721539 0.94286565 0.14639043 0.         0.16230337]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [299]:
import matplotlib.pyplot as plt
color_dtype = np.dtype([
    ('R', np.uint8),  # Red channel
    ('G', np.uint8),  # Green channel
    ('B', np.uint8),  # Blue channel
    ('A', np.uint8)   # Alpha channel
])

color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 255)], dtype=color_dtype)
print(color_array)

[(255,   0, 0, 255) (  0, 255, 0, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [233]:
matrix1 = np.random.randint(1,10,(5,3))
matrix2 = np.random.randint(1,10,(3,2))

print(matrix1 @ matrix2)

[[95 69]
 [49 23]
 [51 23]
 [74 90]
 [82 56]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [7]:
arr = np.random.randint(1,50,size = 10)
mask = (arr < 3) | (arr < 8)
new_arr = arr[mask]

print(new_arr)

[2 3]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [11]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [15]:
Z = np.array([1, 2, 3])

Z**Z  # lega 
2 << Z >> 2  # legal
Z <- Z # legal
1j*Z ## legal
Z/1/1  # legal
Z<Z>Z ## error 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [9]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\resha\AppData\Local\Temp\ipykernel_11012\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\resha\AppData\Local\Temp\ipykernel_11012\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\resha\AppData\Local\Temp\ipykernel_11012\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [17]:
arr = np.array([-1.2, -2.5, -3.7, 1.2, 2.5, 3.7])
rounded = np.where(arr > 0, np.ceil(arr), np.floor(arr))
print(rounded)

[-2. -3. -4.  2.  3.  4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [19]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

common = np.intersect1d(a, b)
print(common)

[3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [21]:
import warnings

warnings.filterwarnings("ignore")
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [23]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [25]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2025-04-21
Today: 2025-04-22
Tomorrow: 2025-04-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [50]:
import pandas as pd

In [52]:
dates = pd.date_range('2016-07-01', '2016-07-31', freq='D')
print(dates)

DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [46]:
A = np.random.rand(5)
B = np.random.rand(5)

A += B  # A = A + B
A *= (-1 * A / 2)  # A = A * (-A / 2)
print(A)

[-1.45957589 -0.81395498 -0.41426228 -1.85927949 -0.02959702]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [44]:
arr = np.random.rand(5) * 10

# Method 1: Using np.floor
int_part1 = np.floor(arr)

# Method 2: Using np.trunc
int_part2 = np.trunc(arr)

# Method 3: Using casting to int
int_part3 = arr.astype(int)

# Method 4: Using np.floor and type casting
int_part4 = np.floor(arr).astype(int)

print(int_part1, int_part2, int_part3, int_part4)

[6. 8. 3. 6. 4.] [6. 8. 3. 6. 4.] [6 8 3 6 4] [6 8 3 6 4]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [28]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [30]:
def int_generator():
    for i in range(10):
        yield i

arr = np.array(list(int_generator()))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [32]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [34]:
vector = np.random.rand(10)
sorted_vector = np.sort(vector)
print(sorted_vector)

[0.01604737 0.06571884 0.20227663 0.23773658 0.25597072 0.27846634
 0.28339097 0.43324351 0.72273242 0.77994055]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [36]:
arr = np.random.rand(1000)

# Using built-in Python sum for small arrays
sum_arr = sum(arr)
print(sum_arr)

517.6042894895685


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [38]:
A = np.random.rand(5)
B = np.random.rand(5)

are_equal = np.array_equal(A, B)
print(are_equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [40]:
arr = np.array([1, 2, 3, 4])
arr.flags.writeable = False
print(arr)

[1 2 3 4]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [42]:
import math

cartesian = np.random.rand(10, 2)

r = np.linalg.norm(cartesian, axis=1)
theta = np.arctan2(cartesian[:, 1], cartesian[:, 0])

polar = np.column_stack((r, theta))
print(polar)

[[0.90794352 1.02594078]
 [0.73751757 0.47625317]
 [0.63278324 0.99900197]
 [1.16428248 1.00895956]
 [0.95540227 0.4692116 ]
 [0.62966114 0.83265635]
 [0.66826193 0.38053302]
 [0.82116892 0.49762641]
 [1.06113437 0.74387936]
 [0.64597166 1.38221793]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [55]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
print(arr)

[0.03687057 0.36394899 0.44511698 0.         0.5802849  0.22913254
 0.7641734  0.67022458 0.29835021 0.11660214]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [57]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)
x, y = np.meshgrid(x, y)

structured_array = np.core.records.fromarrays([x.ravel(), y.ravel()], names='x, y')
print(structured_array)

[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [59]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

C = 1 / (X[:, None] - Y)
print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [61]:
for dtype in [np.int8, np.int16, np.int32, np.int64, np.float32, np.float64]:
    print(f"{dtype}: min = {np.iinfo(dtype).min if np.issubdtype(dtype, np.integer) else np.finfo(dtype).min}, max = {np.iinfo(dtype).max if np.issubdtype(dtype, np.integer) else np.finfo(dtype).max}")

<class 'numpy.int8'>: min = -128, max = 127
<class 'numpy.int16'>: min = -32768, max = 32767
<class 'numpy.int32'>: min = -2147483648, max = 2147483647
<class 'numpy.int64'>: min = -9223372036854775808, max = 9223372036854775807
<class 'numpy.float32'>: min = -3.4028234663852886e+38, max = 3.4028234663852886e+38
<class 'numpy.float64'>: min = -1.7976931348623157e+308, max = 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [63]:
arr = np.random.rand(5)
np.set_printoptions(threshold=np.inf)
print(arr)

[0.92705294 0.97248918 0.73703741 0.6408368  0.5878136 ]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [65]:
arr = np.random.rand(10)
scalar = 0.5
closest_value = arr[np.abs(arr - scalar).argmin()]
print(closest_value)

0.4988500165589089


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [67]:
dtype = np.dtype([('position', '2f8'), ('color', '3f8')])
data = np.array([((1, 2), (0.5, 0.5, 0.5)), ((3, 4), (0.3, 0.6, 0.9))], dtype=dtype)
print(data)

[([1., 2.], [0.5, 0.5, 0.5]) ([3., 4.], [0.3, 0.6, 0.9])]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [69]:
coordinates = np.random.rand(100, 2)
distances = np.linalg.norm(coordinates[1:] - coordinates[:-1], axis=1)
print(distances)

[0.10365458 0.29881357 0.57565901 0.47262868 0.80142795 0.55163399
 0.49695439 0.66340745 0.84018698 0.12072066 0.34816248 0.67215546
 0.39651049 0.3076441  0.44394188 0.42009783 0.27060108 0.60763961
 0.47109668 0.69527627 0.70706615 0.17710324 0.35932943 0.58030302
 0.8994472  0.72672379 0.54922933 0.54868963 0.52521269 0.42638725
 0.20778371 0.43960377 0.81382801 0.15243881 0.7681151  0.16524113
 0.3180932  0.52946697 0.5423807  0.85243449 0.38375272 0.57655866
 0.45872177 0.63581391 0.15319628 0.12458695 0.57427729 0.80468167
 0.76790519 0.61822259 0.2481117  0.30633344 0.29798617 0.34665597
 0.31798367 0.4168317  0.38676677 0.45672042 0.47524001 0.46783778
 0.31888988 0.18466599 0.21553186 0.14615768 0.35880678 0.23075687
 0.95149342 1.03406744 0.76733748 0.69077553 0.75893416 0.63666052
 0.66916281 0.20858847 0.48957142 0.08014354 0.59805636 0.52060039
 0.08317854 0.67820639 0.70525973 0.30193682 0.452552   0.02848646
 0.10214862 0.22544981 0.42388781 0.80761954 0.72250713 0.6834

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [71]:
arr = np.random.rand(10).astype(np.float32)
arr = arr.astype(np.int32)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [75]:
data = np.genfromtxt('file.csv', delimiter=',', filling_values=np.nan)
print(data)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [77]:
arr = np.array([1, 2, 3, 4])
for idx, value in np.ndenumerate(arr):
    print(idx, value)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [79]:
x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)
X, Y = np.meshgrid(x, y)
Z = np.exp(-(X**2 + Y**2) / 2)
print(Z)

[[1.38879439e-11 2.28961804e-11 3.73643128e-11 6.03559147e-11
  9.65053852e-11 1.52739772e-10 2.39288376e-10 3.71073501e-10
  5.69596298e-10 8.65452525e-10 1.30163200e-09 1.93776925e-09
  2.85551720e-09 4.16520494e-09 6.01390891e-09 8.59500616e-09
  1.21591836e-08 1.70267403e-08 2.36008414e-08 3.23811551e-08
  4.39770469e-08 5.91192158e-08 7.86683682e-08 1.03619262e-07
  1.35098250e-07 1.74352359e-07 2.22727996e-07 2.81637620e-07
  3.52513211e-07 4.36746070e-07 5.35613469e-07 6.50193838e-07
  7.81273483e-07 9.29249200e-07 1.09403240e-06 1.27496143e-06
  1.47072943e-06 1.67933523e-06 1.89806416e-06 2.12350484e-06
  2.35160566e-06 2.57777267e-06 2.79700735e-06 3.00407989e-06
  3.19373018e-06 3.36088648e-06 3.50088900e-06 3.60970502e-06
  3.68412164e-06 3.72190330e-06 3.72190330e-06 3.68412164e-06
  3.60970502e-06 3.50088900e-06 3.36088648e-06 3.19373018e-06
  3.00407989e-06 2.79700735e-06 2.57777267e-06 2.35160566e-06
  2.12350484e-06 1.89806416e-06 1.67933523e-06 1.47072943e-06
  1.2749

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [81]:
arr = np.zeros((5, 5))
p = 5
indices = np.random.choice(arr.size, p, replace=False)
np.put(arr, indices, 1)
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [83]:
matrix = np.random.rand(4, 5)
row_means = matrix.mean(axis=1, keepdims=True)
matrix -= row_means
print(matrix)

[[-0.37986902  0.54675419 -0.28223329 -0.10432457  0.21967269]
 [-0.34823265  0.03070341  0.42820718 -0.0072556  -0.10342234]
 [-0.12654537  0.50408843  0.19677765 -0.35105392 -0.2232668 ]
 [-0.40982579  0.15548618 -0.29002718  0.14975558  0.3946112 ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [85]:
array = np.random.rand(5, 5)
n = 2
sorted_array = array[array[:, n].argsort()]
print(sorted_array)

[[0.11993833 0.57508474 0.08964073 0.7891752  0.28985582]
 [0.5204147  0.76047461 0.15126443 0.30528393 0.71624049]
 [0.4399318  0.15092498 0.26547058 0.96638273 0.83997179]
 [0.1542042  0.97027307 0.4088607  0.82552897 0.07825658]
 [0.29595495 0.19403229 0.44964827 0.95160858 0.26037524]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [87]:
array = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 0]])
null_columns = np.all(array == 0, axis=0)
print(null_columns)

[False False False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [89]:
arr = np.array([1, 2, 3, 4, 5])
value = 3.6
nearest = arr[np.abs(arr - value).argmin()]
print(nearest)

4


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [101]:
X = np.array([[1, 2, 3]])
Y = np.array([[1], [2], [3]])

sum_result = np.add(X.T, Y)
print(sum_result)

[[2]
 [4]
 [6]]


#### 63. Create an array class that has a name attribute (★★☆)

In [103]:
class NamedArray(np.ndarray):
    def __new__(cls, shape, dtype=float, name='Unnamed'):
        obj = np.ndarray.__new__(cls, shape, dtype)
        obj.name = name
        return obj

arr = NamedArray((2, 2), name='MyArray')
print(arr.name)

MyArray


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [105]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 3, 2])
arr[indices] += 1
print(arr)

[2 2 4 5 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [107]:
X = np.array([1, 2, 3, 4])
I = np.array([0, 1, 1, 2])
F = np.zeros(3)
np.add.at(F, I, X)
print(F)

[1. 5. 4.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [109]:
image = np.random.randint(0, 256, size=(10, 10, 3), dtype=np.uint8)
unique_colors = np.unique(image.reshape(-1, 3), axis=0)
print(len(unique_colors))

100


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [111]:
arr = np.random.rand(3, 4, 5, 6)
sum_result = arr.sum(axis=(-2, -1))
print(sum_result)

[[16.41063712 14.43315835 15.51042811 15.21124808]
 [14.42964327 15.79445771 16.03455629 14.67216902]
 [12.59900422 13.72815943 15.34485172 15.57565569]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [99]:
image = np.random.randint(0, 256, size=(10, 10, 3), dtype=np.uint8)
unique_colors = np.unique(image.reshape(-1, 3), axis=0)
print(len(unique_colors))

100


#### 69. How to get the diagonal of a dot product? (★★★)

In [5]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

array([2.32737734, 0.80259229, 0.37604657, 1.06133105, 1.21103206])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [119]:
arr = np.array([1, 2, 3, 4, 5])
result = np.zeros(4 * (len(arr) - 1) + len(arr), dtype=int)
result[::4] = arr
print(result)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [123]:
arr1 = np.random.rand(5, 5, 3)
arr2 = np.random.rand(5, 5)
result = arr1 * arr2[:, :, None]
print(result)

[[[0.86339216 0.35081431 0.11935342]
  [0.44918865 0.72580117 0.71776123]
  [0.09472144 0.00590509 0.00100818]
  [0.517371   0.43822762 0.29338379]
  [0.28337957 0.00937282 0.12564092]]

 [[0.23032309 0.05126211 0.15707476]
  [0.03763755 0.30663    0.27580625]
  [0.13635366 0.31947737 0.29223704]
  [0.59161223 0.39802681 0.11519594]
  [0.05193229 0.07056861 0.2247731 ]]

 [[0.1713471  0.25760386 0.07823922]
  [0.11018541 0.12469172 0.21997028]
  [0.00867358 0.00634794 0.00107618]
  [0.09474673 0.25909498 0.06407983]
  [0.05938803 0.12437666 0.03662048]]

 [[0.53104408 0.84333333 0.21050927]
  [0.03541524 0.15903527 0.20790045]
  [0.04297267 0.40325917 0.08540172]
  [0.00930507 0.07519688 0.08190061]
  [0.77358235 0.67768725 0.38927776]]

 [[0.08807894 0.04736281 0.093209  ]
  [0.27319742 0.23518561 0.19148969]
  [0.22264991 0.42268199 0.25846399]
  [0.28027141 0.10917318 0.42777947]
  [0.34021105 0.45204798 0.196233  ]]]


#### 72. How to swap two rows of an array? (★★★)

In [125]:
arr = np.random.rand(5, 5)
arr[[0, 1]] = arr[[1, 0]]  # Swap rows 0 and 1
print(arr)

[[0.52588256 0.95185582 0.62741153 0.20079088 0.82154575]
 [0.03663946 0.84052343 0.44545225 0.05903651 0.37155983]
 [0.32479587 0.89615278 0.59241613 0.70869338 0.69807616]
 [0.95179896 0.62539107 0.18897092 0.90311336 0.59649717]
 [0.89368428 0.60671637 0.38662626 0.08064024 0.57092727]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [127]:
triplets = np.array([(1, 2, 3), (2, 3, 4), (3, 4, 5), (4, 5, 6), (5, 6, 7), (6, 7, 8), (7, 8, 9), (8, 9, 10), (9, 10, 1), (10, 1, 2)])
edges = set()

for t in triplets:
    edges.update([(t[i], t[j]) if t[i] < t[j] else (t[j], t[i]) for i in range(3) for j in range(i+1, 3)])

edges = list(edges)
print(edges)

[(3, 4), (4, 6), (5, 7), (8, 9), (1, 3), (1, 9), (6, 8), (4, 5), (5, 6), (9, 10), (2, 4), (1, 2), (2, 10), (7, 9), (6, 7), (3, 5), (8, 10), (2, 3), (1, 10), (7, 8)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [129]:
C = np.array([2, 3, 5])
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 0 1 1 1 2 2 2 2 2]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [131]:
arr = np.random.rand(10)
window_size = 3
averages = np.convolve(arr, np.ones(window_size)/window_size, mode='valid')
print(averages)

[0.5004946  0.36964192 0.587049   0.5632698  0.44448566 0.2359394
 0.32354114 0.38668861]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [133]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
result = np.array([Z[i:i+3] for i in range(len(Z)-2)])
print(result)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [135]:
arr = np.array([True, False, True])
arr = ~arr  # Negate boolean
print(arr)

arr_float = np.array([1.5, -2.3, 4.0])
arr_float = -arr_float  # Change sign
print(arr_float)

[False  True False]
[-1.5  2.3 -4. ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [137]:
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])
p = np.array([1, 2])

# Vectorized computation of distance from p to each line
dists = np.abs(np.cross(P1 - P0, P0 - p)) / np.linalg.norm(P1 - P0, axis=1)
print(dists)

[2. 1. 0.]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [139]:
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])
P = np.array([[1, 2], [2, 3], [3, 4]])

# Vectorized computation of distance from each point in P to each line
dists = np.abs(np.cross(P1 - P0, P0 - P[:, None])) / np.linalg.norm(P1 - P0, axis=1)
print(dists)

[[2. 1. 0.]
 [3. 2. 1.]
 [4. 3. 2.]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [147]:
def extract_subarray(arr, center, shape, fill_value=0):
    slices = tuple(slice(max(center[i] - shape[i]//2, 0), min(center[i] + shape[i]//2 + 1, arr.shape[i])) for i in range(len(center)))
    subarray = arr[slices]
    if subarray.shape != shape:
        result = np.full(shape, fill_value)
        result[slices] = subarray
        return result
    return subarray

arr = np.arange(16).reshape(4, 4)
subarray = extract_subarray(arr, (2, 2), (3, 3))
print(subarray)


[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [149]:
Z = np.arange(1, 15)
R = np.array([Z[i:i+4] for i in range(len(Z)-3)])
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [151]:
matrix = np.random.rand(4, 5)
rank = np.linalg.matrix_rank(matrix)
print(rank)


4


#### 83. How to find the most frequent value in an array?

In [153]:
arr = np.array([1, 2, 3, 3, 4, 4, 4, 5])
most_frequent = np.bincount(arr).argmax()
print(most_frequent)


4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [155]:
matrix = np.random.rand(10, 10)
blocks = np.lib.stride_tricks.as_strided(matrix, shape=(8, 8, 3, 3), strides=matrix.strides*2)
print(blocks)


[[[[0.86773367 0.96525334 0.2707705 ]
   [0.95839463 0.58371053 0.19164694]
   [0.07665941 0.64482016 0.24576053]]

  [[0.96525334 0.2707705  0.42789802]
   [0.58371053 0.19164694 0.66126484]
   [0.64482016 0.24576053 0.40108643]]

  [[0.2707705  0.42789802 0.5524665 ]
   [0.19164694 0.66126484 0.99166447]
   [0.24576053 0.40108643 0.16482292]]

  [[0.42789802 0.5524665  0.40339754]
   [0.66126484 0.99166447 0.67937599]
   [0.40108643 0.16482292 0.55609114]]

  [[0.5524665  0.40339754 0.37135802]
   [0.99166447 0.67937599 0.13016928]
   [0.16482292 0.55609114 0.3059394 ]]

  [[0.40339754 0.37135802 0.76961192]
   [0.67937599 0.13016928 0.2132174 ]
   [0.55609114 0.3059394  0.17538479]]

  [[0.37135802 0.76961192 0.90357085]
   [0.13016928 0.2132174  0.0370848 ]
   [0.3059394  0.17538479 0.87837672]]

  [[0.76961192 0.90357085 0.42682896]
   [0.2132174  0.0370848  0.0448724 ]
   [0.17538479 0.87837672 0.42973696]]]


 [[[0.95839463 0.58371053 0.19164694]
   [0.07665941 0.64482016 0.2457

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [157]:
matrix = np.random.rand(10, 10)
blocks = np.lib.stride_tricks.as_strided(matrix, shape=(8, 8, 3, 3), strides=matrix.strides*2)
print(blocks)


[[[[0.30049819 0.84485468 0.74632129]
   [0.61284488 0.30962219 0.64119956]
   [0.9454339  0.75912573 0.26961572]]

  [[0.84485468 0.74632129 0.8519439 ]
   [0.30962219 0.64119956 0.29794467]
   [0.75912573 0.26961572 0.79328794]]

  [[0.74632129 0.8519439  0.45886429]
   [0.64119956 0.29794467 0.57424514]
   [0.26961572 0.79328794 0.21761575]]

  [[0.8519439  0.45886429 0.0947996 ]
   [0.29794467 0.57424514 0.05965824]
   [0.79328794 0.21761575 0.87572788]]

  [[0.45886429 0.0947996  0.79327864]
   [0.57424514 0.05965824 0.94153643]
   [0.21761575 0.87572788 0.50435468]]

  [[0.0947996  0.79327864 0.92140707]
   [0.05965824 0.94153643 0.89745958]
   [0.87572788 0.50435468 0.84815742]]

  [[0.79327864 0.92140707 0.56751436]
   [0.94153643 0.89745958 0.49151671]
   [0.50435468 0.84815742 0.78863954]]

  [[0.92140707 0.56751436 0.69587211]
   [0.89745958 0.49151671 0.27758916]
   [0.84815742 0.78863954 0.64363315]]]


 [[[0.61284488 0.30962219 0.64119956]
   [0.9454339  0.75912573 0.2696

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [159]:
matrices = np.random.rand(5, 3, 3)  # 5 matrices of shape (3,3)
vectors = np.random.rand(5, 3, 1)   # 5 vectors of shape (3,1)
result = np.sum(matrices @ vectors, axis=0)
print(result)


[[3.17308761]
 [4.10714004]
 [4.06919848]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [161]:
arr = np.random.rand(16, 16)
block_size = 4
block_sum = arr.reshape(4, 4, 4, 4).sum(axis=(2, 3))
print(block_sum)


[[ 7.42914237  7.26033059  8.30908523  7.42456299]
 [ 9.18718342 10.46864079  9.41240805  5.96700323]
 [ 8.71886243  7.31594431 10.02649823  7.78975418]
 [ 8.87080799  8.67064892  6.27225337  8.46822936]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [163]:
def game_of_life(board, iterations):
    for _ in range(iterations):
        neighbors = sum(np.roll(np.roll(board, i, 0), j, 1) for i in range(-1, 2) for j in range(-1, 2)) - board
        board = (neighbors == 3) | (board & (neighbors == 2))
    return board

board = np.random.randint(0, 2, (5, 5))
print(game_of_life(board, 10))


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [165]:
arr = np.random.rand(10)
n = 3
largest = np.partition(arr, -n)[-n:]
print(largest)


[0.81146521 0.90440327 0.91384782]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [167]:
from itertools import product

vectors = [np.array([1, 2]), np.array([3, 4]), np.array([5, 6])]
cartesian_product = np.array(list(product(*vectors)))
print(cartesian_product)


[[1 3 5]
 [1 3 6]
 [1 4 5]
 [1 4 6]
 [2 3 5]
 [2 3 6]
 [2 4 5]
 [2 4 6]]


#### 91. How to create a record array from a regular array? (★★★)

In [170]:
arr = np.array([(1, 'a'), (2, 'b'), (3, 'c')], dtype=[('x', 'i4'), ('y', 'U1')])
record_array = np.core.records.fromarrays(arr.T, names='x,y')
print(record_array)


((1, 'a'), (2, 'b'), (3, 'c'))


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [172]:
Z = np.random.rand(1000000)

# Method 1: Using the power operator
method1 = Z ** 3

# Method 2: Using np.power
method2 = np.power(Z, 3)

# Method 3: Using np.multiply
method3 = np.multiply(np.multiply(Z, Z), Z)

print(method1[:5], method2[:5], method3[:5])


[1.43323442e-02 1.71746782e-02 6.32073513e-04 2.48278852e-02
 2.41722852e-05] [1.43323442e-02 1.71746782e-02 6.32073513e-04 2.48278852e-02
 2.41722852e-05] [1.43323442e-02 1.71746782e-02 6.32073513e-04 2.48278852e-02
 2.41722852e-05]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [175]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 5, 7], [2, 3, 4], [8, 9, 10], [1, 3, 5], [4, 6, 7]])
B = np.array([[2, 3], [5, 6]])

result = [row for row in A if any(set(b).issubset(set(row)) for b in B)]
print(np.array(result))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 1  5  7]
 [ 2  3  4]
 [ 8  9 10]
 [ 1  3  5]
 [ 4  6  7]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [177]:
matrix = np.random.randint(1, 5, (10, 3))
unequal_rows = matrix[np.any(matrix != matrix[:, [0]], axis=1)]
print(unequal_rows)


[[1 2 4]
 [2 3 1]
 [3 4 2]
 [4 4 1]
 [3 3 1]
 [3 4 1]
 [3 3 1]
 [3 1 4]
 [2 3 4]
 [2 3 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [179]:
arr = np.array([1, 2, 3, 4])
binary_matrix = np.array([list(format(i, '08b')) for i in arr], dtype=int)
print(binary_matrix)


[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [181]:
matrix = np.random.randint(1, 5, (5, 3))
unique_rows = np.unique(matrix, axis=0)
print(unique_rows)


[[3 1 3]
 [3 2 3]
 [3 4 4]
 [4 2 4]
 [4 4 2]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [183]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Inner product
inner = np.einsum('i,i->', A, B)

# Outer product
outer = np.einsum('i,j->ij', A, B)

# Sum
sum_result = np.einsum('i->', A)

# Element-wise multiplication
mul = np.einsum('i,i->i', A, B)

print(inner, outer, sum_result, mul)


32 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]] 6 [ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [185]:
X = np.array([0, 1, 2, 3])
Y = np.array([0, 1, 4, 9])

# Parametrize the path
distances = np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
distances = np.insert(distances, 0, 0)

# Sample equidistant points
n_samples = 5
target_distances = np.linspace(0, distances[-1], n_samples)
sampled_X = np.interp(target_distances, distances, X)
sampled_Y = np.interp(target_distances, distances, Y)

print(sampled_X, sampled_Y)


[0.         1.31770269 2.05123811 2.52561906 3.        ] [0.         1.95310807 4.25619057 6.62809529 9.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
n = 5
X = np.random.randint(0, 10, (10, 3))

valid_rows = X[np.all(np.mod(X, 1) == 0, axis=1) & (X.sum(axis=1) == n)]
print(valid_rows)


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)